language: crystal
addons:
  chrome: stable
services:
  - postgresql
before_install:
  # Setup chromedriver for LuckyFlow
  - sudo apt-get install chromium-chromedriver

  # Setup assets
  - yarn install
  - yarn prod
script:
  - crystal spec
  # Uncomment the next line if you'd like Travis to check code formatting
  # - crystal tool format spec src --check
cache:
  yarn: true
  directories:
    - bin/lucky
    - lib
    - .shards
